import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from '@/providers'
import '@/styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

// eslint-disable-next-line react-refresh/only-export-components
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  themeColor: '#ffffff',
  icons: [
    {
      url: '/favicon-32x32.png',
      sizes: '32x32',
    },
    {
      url: '/favicon-16x16.png',
      sizes: '16x16',
    },
  ],
  viewport: {
    initialScale: 1,
    width: 'device-width',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`bg-white dark:bg-black ${inter.className} min-h-[100dvh] flex flex-col`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
