import type { Metadata } from 'next'
import { GeistMono } from 'geist/font/mono'
import { GeistSans } from 'geist/font/sans'
import Providers from '@/providers'
import '@/styles/globals.css'

// eslint-disable-next-line react-refresh/only-export-components
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: [
    {
      url: '/favicon-32x32.png',
      sizes: '32x32',
    },
    {
      url: '/favicon-16x16.png',
      sizes: '16x16',
    },
  ],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${GeistSans.variable} ${GeistMono.variable}`}
    >
      <body
        className={`min-h-[100dvh] flex flex-col antialiased bg-background`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
